#!/usr/bin/env python3

import sys

import lexer
import astparse

with open(sys.argv[1], 'r') as file:
    tokens = lexer.Lexer(file.read()).lex()
tree = astparse.generate_tree(tokens)
response = astparse.run(tree)
